language: java
sudo: false

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
  - openjdk7

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: "eSWiy/8+n38mgl02uuLeKlMe+065tsXmSA1okBESIWREVUgtLXbPgZfCcsHs\nlEJcAGu501QEJt4WYo6yDufn1p/5K1fCI4ogLDsbSpWfwkkMs4Bqj1TmGrlq\njogUTslOdhuCCXkz9vAm7cQvBGLsclFVoxhJZmAuaB1MBTxA+XI="
    - secure: "O11chFb/7lsXuIbqZVs9LWLUSQz86Nn6dzVTLtcWhWlnlkzkVxDWa5bVwsf9\nVVnyLPV/9S5PCWR/HR4bfGTHxM0IufcK89niPBzcMu24nwGVLwSz6QLdh2AG\n1tn0Ji8zNp7yck8fZIlKITMGYE+vAZfJ/B9E1JtOHSDz9us3WpQ="
